config/routes.rb
Rails.application.routes.draw do
  resources :libros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    if params[:estado].present?
      @libros = Libro.where('estado = ?', params[:estado])
else
     @libros = Libro.all.order("title ASC")
  end
end



  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:title, :author, :estado, :fecha_prestamo, :fecha_devoulto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiblioApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/libros/_form.html.erb
<%= form_with(model: libro, local: true) do |form| %>
  <% if libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="text-center">
   <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

 <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

   <div class="form-group">
    <%= form.label :estado%>
    <%= form.select :estado, options_for_select(['en estante', 'prestado'])%>

  </div>


 <div class="form-group">
    <%= form.label :fecha_prestamo %>
    <%= form.date_select :fecha_prestamo %>
  </div>

 <div class="form-group">
    <%= form.label :fecha_devoulto %>
    <%= form.date_select :fecha_devoulto %>
  </div>

  <div class="actions">
    <button type="button" class="btn text-white bg-dark "><%= form.submit %></button>
  </div>


<% end %>
  </div>

app/views/libros/edit.html.erb
<h1 class="text-center m-4 text-dark"> Editing Libro</h1>
<div class="text-center">

<%= render 'form', libro: @libro %>
<%= link_to 'Show', @libro %>|
<%= link_to 'New Libro', new_libro_path %>


</div>

app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>


<h1 class="text-center m-4 text-dark"> LIbros</h1>
<nav class="navbar navbar-light bg-light justify-content-between">
<a class="navbar-brand"> <h3>Elige status de los  libros:  en estante o prestado</h3></a>
<form class="form-inline">
<input class="form-control mr-sm-2" type="search" placeholder="Search"
aria-label="Estado" name="estado">
<button class="btn btn-outline-success my-2 my-sm-0"
type="submit">Search</button>
</form>
</nav>

    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Estado</th>
      <th>Fecha prestamo</th>
      <th>Fecha devoulto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.title %></td>
        <td><%= libro.author %></td>
        <td><%= libro.estado %></td>
        <td><%= libro.fecha_prestamo %></td>
        <td><%= libro.fecha_devoulto %></td>
        <td><%= link_to 'Show', libro %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn text-white bg-dark "><%= link_to 'New Libro', new_libro_path %></button>

app/views/libros/new.html.erb
<h1 class="text-center m-4 text-dark"> New Libro</h1>
<div class="text-center">
<%= render 'form', libro: @libro %>

<%= link_to 'Back', libros_path %>
</div>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card" style="width: 18rem;">

  <div class="card-body">
    <h5 class="card-title">Title</h5>
    <p class="card-text"><%= @libro.title %></p>
    <h5 class="card-title">Author</h5>
    <p class="card-text"><%= @libro.author %></p>
    <h5 class="card-title">Estado</h5>
    <p class="card-text"><%= @libro.estado %></p>
    <h5 class="card-title">Fecha prestamo</h5>
    <p class="card-text"><%= @libro.fecha_devoulto %></p>
    <h5 class="card-title">Fecha devoulto</h5>
    <p class="card-text"><%= @libro.fecha_prestamo %></p>
    <br>
    <%= link_to 'Edit', edit_libro_path(@libro) %> |
    <%= link_to 'Back', libros_path %>

  </div>
</div>